name: Build test

on:
  # Trigger the workflow on push or pull requests.
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      FLAGS: -g -O2 -Wall -Wextra -Werror

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Display compiler versions
      run: |
        ${{matrix.cc}} --version
        ${{matrix.cxx}} --version

    - name: Build
      run: |
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}}
        make V=1 -j$(nproc) \
             CPPFLAGS="-Werror" \
             CFLAGS="$FLAGS" \
             CXXFLAGS="$FLAGS"

    - name: Test install command
      run: |
        sudo make install
